// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, content string) (Note, error)
	DeleteNoteByID(ctx context.Context, id int32) error
	GetNoteByID(ctx context.Context, id int32) (Note, error)
	ListNotes(ctx context.Context) ([]Note, error)
	UpdateNoteByID(ctx context.Context, arg UpdateNoteByIDParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
