// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (content) VALUES ($1) RETURNING id, content, created_at
`

func (q *Queries) CreateNote(ctx context.Context, content string) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, content)
	var i Note
	err := row.Scan(&i.ID, &i.Content, &i.CreatedAt)
	return i, err
}

const deleteNoteByID = `-- name: DeleteNoteByID :exec
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNoteByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNoteByID, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, content, created_at FROM notes WHERE id = $1
`

func (q *Queries) GetNoteByID(ctx context.Context, id int32) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(&i.ID, &i.Content, &i.CreatedAt)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, content, created_at FROM notes
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.Content, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoteByID = `-- name: UpdateNoteByID :one
UPDATE notes SET content = $2 WHERE id = $1 RETURNING id, content, created_at
`

type UpdateNoteByIDParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateNoteByID(ctx context.Context, arg UpdateNoteByIDParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNoteByID, arg.ID, arg.Content)
	var i Note
	err := row.Scan(&i.ID, &i.Content, &i.CreatedAt)
	return i, err
}
